# Generated by Django 3.2 on 2021-04-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('address_line_1', models.CharField(max_length=264)),
                ('address_line_2', models.CharField(blank=True, max_length=264, null=True)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=64)),
                ('pincode', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
