# Generated by Django 3.2 on 2021-04-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='quantity_remaining',
        ),
        migrations.AddField(
            model_name='supply',
            name='blood_group',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='icu_bed_count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='supply',
            name='normal_bed_count',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='supply',
            name='oxygen_supply_type',
            field=models.CharField(blank=True, choices=[('CON', 'Concentrator'), ('REF', 'Refill'), ('EMP', 'Empty Cylinder'), ('FIL', 'Filled Cylinder')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='primary_contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='supply',
            name='secondary_contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply_type',
            field=models.CharField(choices=[('PLM', 'Plasma'), ('BLD', 'Blood'), ('OXY', 'OXYGEN'), ('HFD', 'Home Food'), ('HBD', 'Hospital Bed'), ('ICU', 'ICU Bed')], max_length=3),
        ),
    ]
