# Generated by Django 3.2 on 2021-04-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplies', '0002_auto_20210426_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='other_spam_reason',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='spam_reason',
            field=models.CharField(blank=True, choices=[('MY_CONTACT', 'My Contact'), ('WRONG_CONTACT', 'Wrong Contact'), ('VERIFIED_WRONG', 'Verified wrong information'), ('OTHER', 'Some other reason')], max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='spam_report_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supply',
            name='unavailable_report_count',
            field=models.IntegerField(default=0),
        ),
    ]
