# Generated by Django 3.2 on 2021-04-22 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
        ('Requirements', '0002_auto_20210422_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Common.address'),
        ),
    ]
